name: GHA-demo
on:
 push:
    branches:
    - main
    - release/*
jobs:
  check-os: 
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: uname -u 
        shell: bash

    
    
   
